[[redirects]]
    from = "https://kuxir.xyz/jeuxdebloques"
    to = "https://jeuxdebloques.online/"
    status = 301
    force = true
    
[[redirects]]
    from = "/gh/*"
    to = "https://github.com/luigigeek12/:splat"
    status = 301
    force = true
